package codes.quine.labo.unref

class RESuite extends munit.FunSuite:
  test("RE#toString") {
    assertEquals(RE.Lit('x').toString, "x")
    assertEquals(RE.Lit('\\').toString, "\\\\")
    assertEquals(RE.Assert(AssertKind.InputBegin).toString, "^")
    assertEquals(RE.Assert(AssertKind.InputEnd).toString, "$")
    assertEquals(RE.Assert(AssertKind.WordBoundary).toString, "\\b")
    assertEquals(RE.Assert(AssertKind.NotWordBoundary).toString, "\\B")
    assertEquals(RE.Cat().toString, "")
    assertEquals(RE.Cat(RE.Lit('x'), RE.Lit('y')).toString, "xy")
    assertEquals(RE.Cat(RE.Cat(RE.Lit('x'), RE.Lit('y')), RE.Lit('z')).toString, "(?:xy)z")
    assertEquals(RE.Cat(RE.Alt(RE.Lit('x'), RE.Lit('y')), RE.Lit('z')).toString, "(?:x|y)z")
    assertEquals(RE.Alt().toString, "(?!)")
    assertEquals(RE.Alt(RE.Lit('x'), RE.Lit('y')).toString, "x|y")
    assertEquals(RE.Alt(RE.Alt(RE.Lit('x'), RE.Lit('y')), RE.Lit('z')).toString, "(?:x|y)|z")
    assertEquals(RE.PosLA(RE.Lit('x')).toString, "(?=x)")
    assertEquals(RE.NegLA(RE.Lit('x')).toString, "(?!x)")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Star, true).toString, "x*")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Star, false).toString, "x*?")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Plus, true).toString, "x+")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Plus, false).toString, "x+?")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Question, true).toString, "x")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Question, false).toString, "x?")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Exact(1), true).toString, "x{1}")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Exact(1), false).toString, "x{1}?")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Unbounded(1), true).toString, "x{1,}")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Unbounded(1), false).toString, "x{1,}?")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Bounded(1, 2), true).toString, "x{1,2}")
    assertEquals(RE.Rep(RE.Lit('x'), Quantifier.Bounded(1, 2), false).toString, "x{1,2}?")
    assertEquals(RE.Rep(RE.Cat(RE.Lit('x'), RE.Lit('y')), Quantifier.Star, true).toString, "(?:xy)*")
    assertEquals(RE.Rep(RE.Alt(RE.Lit('x'), RE.Lit('y')), Quantifier.Star, true).toString, "(?:x|y)*")
    assertEquals(RE.Rep(RE.Rep(RE.Lit('x'), Quantifier.Star, true), Quantifier.Star, true).toString, "(?:x*)*")
  }
